version: 2
jobs:
  build:
    working_directory: ~/btc2fiat
    docker:
      - image: circleci/python:3.7-rc-node
    steps:
      - checkout
      - restore_cache:
          key: dep-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: dep-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            cd tests && python test.py